const data = {
	bigCards: {
		cards: [
			{
				id: "fb",
				platform: "./images/icon-facebook.svg",
				userHandle: "@nathanf",
				numOfFollowers: "1987",
				label: "followers",
				gainOrLossIcon: "./images/icon-up.svg",
				gainOrLossNumber: "12 Today",
				borderTop: "5px solid hsl(208, 92%, 53%)",
				textColor: "hsl(163, 72%, 41%)",
			},
			{
				id: "tw",
				platform: "./images/icon-twitter.svg",
				userHandle: "@nathanf",
				numOfFollowers: "1044",
				label: "followers",
				gainOrLossIcon: "./images/icon-up.svg",
				gainOrLossNumber: "99 Today",
				borderTop: "5px solid hsl(203, 89%, 53%)",
				textColor: "hsl(163, 72%, 41%)",
			},
			{
				id: "ig",
				platform: "./images/icon-instagram.svg",
				userHandle: "@realnathanf",
				numOfFollowers: "11K",
				label: "followers",
				gainOrLossIcon: "./images/icon-up.svg",
				gainOrLossNumber: "1099 Today",
				borderTop: "5px solid hsl(37, 97%, 70%)",
				textColor: "hsl(163, 72%, 41%)",
			},
			{
				id: "yt",
				platform: "./images/icon-youtube.svg",
				userHandle: "@nathanf",
				numOfFollowers: "1987",
				label: "subscribers",
				gainOrLossIcon: "./images/icon-down.svg",
				gainOrLossNumber: "144 Today",
				borderTop: "5px solid hsl(348, 97%, 39%)",
				textColor: "hsl(356, 69%, 56%)",
			},
		],
	},
	smallCards: {
		cards: [
			{
				platform: "./images/icon-facebook.svg",
				number: "87",
				label: "Page Views",
				gainOrLossIcon: "./images/icon-up.svg",
				gainOrLossNumber: "3%",
				textColor: "hsl(163, 72%, 41%)",
			},
			{
				platform: "./images/icon-facebook.svg",
				number: "52",
				label: "Likes",
				gainOrLossIcon: "./images/icon-down.svg",
				gainOrLossNumber: "2%",
				textColor: "hsl(356, 69%, 56%)",
			},
			{
				platform: "./images/icon-instagram.svg",
				number: "5462",
				label: "Likes",
				gainOrLossIcon: "./images/icon-up.svg",
				gainOrLossNumber: "2257%",
				textColor: "hsl(163, 72%, 41%)",
			},
			{
				platform: "./images/icon-instagram.svg",
				number: "52k",
				label: "Profile Views",
				gainOrLossIcon: "./images/icon-up.svg",
				gainOrLossNumber: "1375%",
				textColor: "hsl(163, 72%, 41%)",
			},
			{
				platform: "./images/icon-twitter.svg",
				number: "117",
				label: "Retweets",
				gainOrLossIcon: "./images/icon-up.svg",
				gainOrLossNumber: "303%",
				textColor: "hsl(163, 72%, 41%)",
			},
			{
				platform: "./images/icon-twitter.svg",
				number: "507",
				label: "Likes",
				gainOrLossIcon: "./images/icon-up.svg",
				gainOrLossNumber: "553%",
				textColor: "hsl(163, 72%, 41%)",
			},
			{
				platform: "./images/icon-youtube.svg",
				number: "107",
				label: "Likes",
				gainOrLossIcon: "./images/icon-down.svg",
				gainOrLossNumber: "19%",
				textColor: "hsl(356, 69%, 56%)",
			},
			{
				platform: "./images/icon-youtube.svg",
				number: "1407",
				label: "Total Views",
				gainOrLossIcon: "./images/icon-down.svg",
				gainOrLossNumber: "12%",
				textColor: "hsl(356, 69%, 56%)",
			},
		],
	},
};

export default data;
